// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"tdd/core"
	"tdd/fizzbuzz_sequence_printer_good"
)

// Injectors from wire.go:

func InitializeFizzBuzzPrinter() (*fizzbuzzsequenceprintergood.FizzBuzzSequencePrinter, error) {
	v := fizzbuzzsequenceprintergood.ProvideRules()
	numberConverter := core.NewNumberConverter(v)
	outputInterface := fizzbuzzsequenceprintergood.NewConsoleOutput()
	fizzBuzzSequencePrinter := fizzbuzzsequenceprintergood.NewFizzBuzzSequencePrinter(numberConverter, outputInterface)
	return fizzBuzzSequencePrinter, nil
}
