// Code generated by MockGen. DO NOT EDIT.
// Source: fizzbuzz_sequence_printer_good/fizzbuzz_sequence_printer.go
//
// Generated by this command:
//
//	mockgen -source=fizzbuzz_sequence_printer_good/fizzbuzz_sequence_printer.go -destination=fizzbuzz_sequence_printer_good/mock_printer.go -package=fizzbuzz_sequence_printer_good
//

// Package fizzbuzz_sequence_printer_good is a generated GoMock package.
package fizzbuzzsequenceprintergood

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockNumberConverter is a mock of NumberConverter interface.
type MockNumberConverter struct {
	ctrl     *gomock.Controller
	recorder *MockNumberConverterMockRecorder
	isgomock struct{}
}

// MockNumberConverterMockRecorder is the mock recorder for MockNumberConverter.
type MockNumberConverterMockRecorder struct {
	mock *MockNumberConverter
}

// NewMockNumberConverter creates a new mock instance.
func NewMockNumberConverter(ctrl *gomock.Controller) *MockNumberConverter {
	mock := &MockNumberConverter{ctrl: ctrl}
	mock.recorder = &MockNumberConverterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNumberConverter) EXPECT() *MockNumberConverterMockRecorder {
	return m.recorder
}

// Convert mocks base method.
func (m *MockNumberConverter) Convert(n int) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Convert", n)
	ret0, _ := ret[0].(string)
	return ret0
}

// Convert indicates an expected call of Convert.
func (mr *MockNumberConverterMockRecorder) Convert(n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Convert", reflect.TypeOf((*MockNumberConverter)(nil).Convert), n)
}

// MockOutputInterface is a mock of OutputInterface interface.
type MockOutputInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOutputInterfaceMockRecorder
	isgomock struct{}
}

// MockOutputInterfaceMockRecorder is the mock recorder for MockOutputInterface.
type MockOutputInterfaceMockRecorder struct {
	mock *MockOutputInterface
}

// NewMockOutputInterface creates a new mock instance.
func NewMockOutputInterface(ctrl *gomock.Controller) *MockOutputInterface {
	mock := &MockOutputInterface{ctrl: ctrl}
	mock.recorder = &MockOutputInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutputInterface) EXPECT() *MockOutputInterfaceMockRecorder {
	return m.recorder
}

// write mocks base method.
func (m *MockOutputInterface) write(data string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "write", data)
}

// write indicates an expected call of write.
func (mr *MockOutputInterfaceMockRecorder) write(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "write", reflect.TypeOf((*MockOutputInterface)(nil).write), data)
}
